In [1]:
import os
import sys
sys.path.append(os.getcwd())

from lib.models.model_execution_support import run_on_inputs_with_targets
from lib.models.model_execution_support import run_mod_with_correction_block_on_inputs_with_targets
from lib.models.recurrent_forecaster_with_correction_block import RecurrentForecasterWithCorrectionBlock
from lib.models.recurrent_sigmoid_piecewise_forecaster import RSPForecaster
from lib.models.linear_forecaster import LinearForecaster
from lib.utils.recurrent_contexts_manager import RecurrentContextsManager

import numpy as np
import pandas as pd
import torch

In [2]:
DEVICE = 'cpu'
DTYPE = torch.float32

In [3]:
INP_SIZE = 2

def sw(t: torch.Tensor) -> torch.Tensor:
    return t.unfold(dimension=1, size=INP_SIZE, step=1)


def get_train_test_data_heart_rate(heart_data, train_ratio=0.9):
    N = heart_data.shape[1]
    train_size = int(N * train_ratio)
    test_size = N - train_size
    train_ts = heart_data[:, :train_size]
    test_ts = heart_data[:, train_size:]
    return (
        sw(torch.from_numpy(train_ts[:, :-1])).permute(1, 0, 2).to(DEVICE, dtype=DTYPE),
        torch.from_numpy(train_ts[:, INP_SIZE:]).permute(1, 0).unsqueeze(-1).to(DEVICE, dtype=DTYPE),
        sw(torch.from_numpy(test_ts[:, :-1])).permute(1, 0, 2).to(DEVICE, dtype=DTYPE),
        torch.from_numpy(test_ts[:, INP_SIZE:]).permute(1, 0).unsqueeze(-1).to(DEVICE, dtype=DTYPE),
    )

df = pd.read_csv('heart_rate.csv')
print(df['T4'][890])
heart_data = np.array(df[:891]).transpose(1, 0)
heart_data = heart_data / (heart_data.max() - heart_data.min())
heart_data = heart_data - heart_data.mean()
print(heart_data)
print(heart_data.shape)

62.0
[[ 0.14598108  0.14598108  0.14204635 ...  0.4683017   0.45550151
   0.43827048]
 [ 0.28219521  0.28219521  0.27689336 ...  0.40076932  0.38879281
   0.38256881]
 [-0.30440775 -0.30440775 -0.30484894 ... -0.36155229 -0.35393276
  -0.34546305]
 [-0.32704289 -0.32704289 -0.32704289 ... -0.29516359 -0.26901976
  -0.2757001 ]]
(4, 891)


In [4]:
inp_len_test = 4
num_sequences_test = 9

cm = RecurrentContextsManager()
pred = LinearForecaster(cm, inp_len_test)
inp_test = torch.randn(num_sequences_test, inp_len_test, device=DEVICE, dtype=DTYPE)
out_test = pred(inp_test)

print(out_test.shape)
print(out_test)
print(pred.predictor.weight.shape)

torch.Size([9, 1])
tensor([[ 0.6499],
        [-0.0303],
        [ 1.1293],
        [-0.2971],
        [ 0.2109],
        [ 0.1549],
        [ 0.1807],
        [ 0.1886],
        [ 0.8036]], grad_fn=<AddmmBackward0>)
torch.Size([1, 4])


In [5]:
inp_len_test = 4
hidden_size_test = 8
num_sequences_test = 9

cm = RecurrentContextsManager()
pred = RSPForecaster(cm, inp_len_test, hidden_size_test)
pred.init_context(num_sequences_test, device=DEVICE)
print(id(cm.get_ctx(pred.cid)))
print(cm.get_ctx(pred.cid))
inp1_test = torch.randn(num_sequences_test, inp_len_test, device=DEVICE, dtype=DTYPE)
prev_errors1_test = torch.randn(num_sequences_test, 1, device=DEVICE, dtype=DTYPE) * 0.1
out1_test = pred(inp_test)
print(id(cm.get_ctx(pred.cid)))
print(cm.get_ctx(pred.cid))
gt1_test = out_test + torch.randn(num_sequences_test, 1, device=DEVICE, dtype=DTYPE) * 0.1
inp2_test = torch.randn(num_sequences_test, inp_len_test, device=DEVICE, dtype=DTYPE)
out2_test = pred(inp2_test)
print(id(cm.get_ctx(pred.cid)))
print(cm.get_ctx(pred.cid))


print(out1_test.shape)
print(out1_test)
print(out2_test.shape)
print(pred.sigm_lin.weight.shape)

139690023682752
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
139690022908448
tensor([[ 0.0051,  0.1282, -0.2462, -0.0509, -0.0644, -0.1124, -0.1760, -0.0957],
        [ 0.1840, -0.1408,  0.1254, -0.2304,  0.7414, -0.0419,  0.1285, -0.1078],
        [-0.0425,  0.1827, -0.6884,  0.0443, -0.2545, -0.1685, -0.3489, -0.1044],
        [ 0.0617, -0.0714,  0.0724, -0.2136,  0.3363, -0.1799, -0.0496, -0.0934],
        [-0.1412,  0.1159, -0.4529, -0.0650, -0.1943, -0.3191, -0.2947, -0.0764],
        [ 0.0326,  0.0877, -0.2067,  0.0112, -0.1403, -0.1450, -0.1900, -0.0833],
        [ 0.0995, -0.0226,  0.0861, -0.1714,  0.4567, -0.0547,  0.0775, -0.0970],
        [ 0.398

In [6]:
train_inp, train_targ, test_inp, test_targ = get_train_test_data_heart_rate(heart_data)
print(train_inp.shape)
print(train_targ.shape)
print(test_inp.shape)
print(test_targ.shape)

HIDDEN_SIZE = 8
cm = RecurrentContextsManager()
pred = RSPForecaster(cm, INP_SIZE, HIDDEN_SIZE)
outs_train = run_on_inputs_with_targets(pred, train_inp, train_targ)
print(outs_train.shape)
outs_test = run_on_inputs_with_targets(pred, test_inp, test_targ)
print(outs_test.shape)

torch.Size([799, 4, 2])
torch.Size([799, 4, 1])
torch.Size([88, 4, 2])
torch.Size([88, 4, 1])
torch.Size([799, 4, 1])
torch.Size([88, 4, 1])


In [7]:
cm = RecurrentContextsManager()
baseline = LinearForecaster(cm, INP_SIZE)
# INP_SIZE + 3 because correction block also takes baseline
# forecast, previous baseline error and previous actual
# error as extra inputs
corrector = RSPForecaster(cm, INP_SIZE + 3, HIDDEN_SIZE)
pred = RecurrentForecasterWithCorrectionBlock(cm, baseline, corrector)
outs_train = run_mod_with_correction_block_on_inputs_with_targets(pred, train_inp, train_targ)
print(outs_train.shape)
outs_test = run_mod_with_correction_block_on_inputs_with_targets(pred, test_inp, test_targ)
print(outs_test.shape)

torch.Size([799, 4, 1])
torch.Size([88, 4, 1])
